darkube_build_khadije-charity-site_yaqoot-sabz_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
      - main
  script:
    - IMAGE_ADDRESS="registry.hamdocker.ir/yaqoot-sabz/khadije-charity-site"
    - 'darkube build --push -t $IMAGE_ADDRESS:$CI_COMMIT_SHORT_SHA -t $IMAGE_ADDRESS:$CI_COMMIT_REF_SLUG
    --workdir . --file ./Dockerfile --build-context . '
  stage: build
darkube_deploy_khadije-charity-site_yaqoot-sabz_hamravesh-c13:
  image: hamravesh.hamdocker.ir/public/darkube-cli:v1.1
  interruptible: true
  only:
    refs:
      - main
  script:
    - darkube deploy --token ${DEPLOY_TOKEN_KHADIJE_CHARITY_SITE_YAQOOT_SABZ_HAMRAVESH_C13}
      --app-id ${APP_ID_KHADIJE_CHARITY_SITE_YAQOOT_SABZ_HAMRAVESH_C13} --image-tag
      ${CI_COMMIT_SHORT_SHA} --job-id ${CI_JOB_ID}
  stage: deploy